### PR TITLE
use platform-python for dnf provenance generation

### PR DESCRIPTION
**Pull request by Habbie**
This PR changes two files. *Either* change fixes the problem (`import dnf` failing in the provenance script), so we need to choose.

### CODE REVIEW

**Comment by Habbie** [comment]
```
09:29Z <zeha> Habbie: if you need to use dnf from python (and thats a valid api), it would seem to be sensible to use usr/libexec/platform-python 
09:29Z <zeha> Habbie: might want a comment 
```

**Comment by wojas** [comment]
The `platform-python` approach is more robust than pinning it to a python version that has been EOL for over 2 years.

We are currently missing EL 9 in the tests.

**Comment by Habbie** [comment]
> The `platform-python` approach is more robust than pinning it to a python version that has been EOL for over 2 years.

Yes, agreed. Will take out the other change.

**Comment by Habbie** [comment]
done

**Review by wojas — APPROVED** [review]

**Pull request merged**
